name: flutter_sanity_image_url
description: A flutter package to quickly generate sanity image urls.
version: 0.0.1
homepage: https://github.com/techurve/flutter_sanity_image_url
repository: https://github.com/techurve/flutter_sanity_image_url

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.20.2
