name: flutter_sanity_image_url
description: A fork of flutter_sanity_image_url - Flutter package for displaying images from Sanity CMS with useful metadata like LQIP and color palette. Install from GitHub.
version: 0.1.0
homepage: https://github.com/dbethel/flutter_sanity_image_url
repository: https://github.com/dbethel/flutter_sanity_image_url
issue_tracker: https://github.com/dbethel/flutter_sanity_image_url/issues

environment:
  sdk: ">=2.17.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.20.2
